config/routes.rb
Rails.application.routes.draw do
  resources :characters
  resources :skills
  
  devise_for :users, :controllers => { :registrations => "user/registrations" }
  get 'welcome/index'

  root 'welcome#index'

end

app/models/character.rb
class Character < ActiveRecord::Base
  has_many :skills
  has_many :merits
  has_many :conditions
  
  def get_skills
    skills = Skill.where(character_id: self.id)
    if skills.size <= 0
      return populate_skills;
    end    
    return skills;
  end
  
  def populate_skills
    skills = Array.new(24);
    skills[0] = Skill.new(:name => "Academics", :value => 0, :character_id => self)
    skills[1] = Skill.new(:name => "Computer", :value => 0, :character_id => self)
    skills[2] = Skill.new(:name => "Crafts", :value => 0, :character_id => self)
    skills[3] = Skill.new(:name => "Investigation", :value => 0, :character_id => self)
    skills[4] = Skill.new(:name => "Medicine", :value => 0, :character_id => self)
    skills[5] = Skill.new(:name => "Occult", :value => 0, :character_id => self)
    skills[6] = Skill.new(:name => "Politics", :value => 0, :character_id => self)
    skills[7] = Skill.new(:name => "Science", :value => 0, :character_id => self)
    
    skills[8] = Skill.new(:name => "Athletics", :value => 0, :character_id => self)
    skills[9] = Skill.new(:name => "Brawl", :value => 0, :character_id => self)
    skills[10] = Skill.new(:name => "Drive", :value => 0, :character_id => self)
    skills[11] = Skill.new(:name => "Firearms", :value => 0, :character_id => self)
    skills[12] = Skill.new(:name => "Larceny", :value => 0, :character_id => self)
    skills[13] = Skill.new(:name => "Stealth", :value => 0, :character_id => self)
    skills[14] = Skill.new(:name => "Survival", :value => 0, :character_id => self)
    skills[15] = Skill.new(:name => "Weaponry", :value => 0, :character_id => self)
    
    skills[16] = Skill.new(:name => "Animal Ken", :value => 0, :character_id => self)
    skills[17] = Skill.new(:name => "Empathy", :value => 0, :character_id => self)
    skills[18] = Skill.new(:name => "Expression", :value => 0, :character_id => self)
    skills[19] = Skill.new(:name => "Intimidation", :value => 0, :character_id => self)
    skills[20] = Skill.new(:name => "Persuasion", :value => 0, :character_id => self)
    skills[21] = Skill.new(:name => "Socialize", :value => 0, :character_id => self)
    skills[22] = Skill.new(:name => "Streetwise", :value => 0, :character_id => self)
    skills[23] = Skill.new(:name => "Subterfuge", :value => 0, :character_id => self)
    
    skillsList = "";
    skills.each do |s|
      if(s != nil)
        skillsList += ", #{s.name}"
      end
    end
    puts skillsList;
    
    return skills;
  end
  
  def skills_defined_in_character(character)
    if self.user_items.pending.select {|s| s.user == user}.count > 0 
      return true
    else
      return false
    end
  end
end

app/models/condition.rb
class Condition < ActiveRecord::Base
end

app/models/merit.rb
class Merit < ActiveRecord::Base
end

app/models/skill.rb
class Skill < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, 
         :validatable, authentication_keys: [:login]
  
  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login
  
  validates :username, presence: :true, uniqueness: { case_sensitive: false }
  # Only allow letter, number, underscore and punctuation.
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  validate :validate_username
  
  has_many :character
  
  #def new
  #  #@user = User.new
  #end
  #
  #def create
  #  if verify_recaptcha
  #    #render 'show'
  #  else
  #    #@user = User.new
  #    #render 'new'
  #  end
  #end

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end
  
  def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      elsif conditions.has_key?(:username) || conditions.has_key?(:email)
        where(conditions.to_hash).first
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:edit, :update, :show, :destroy]
  
  def show
  end
  
  def new
    @character = Character.new
  end
  
  def create
    @character = Character.new(character_params)
    @character.user = current_user
    if(@character.save)
      flash[:success] = "Character was successfully created"
      #redirect_to article_path(@article)
    else
      #render 'new'
    end
  end
  
  private
    def set_character
      @character = Character.find(params[:id])
    end
  
    def character_params
      params.require(:character).permit!
    end
  
end

app/controllers/user/registrations_controller.rb
#class User::RegistrationsController < Devise::RegistrationsController
#  
#  before_action :configure_permitted_parameters
#  
#  protected
#  
#  def configure_permitted_parameters
#    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
#    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
#  end
#  
#end
#

class User::RegistrationsController < Devise::RegistrationsController
  
  #prepend_before_action :configure_permitted_parameters
  prepend_before_action :check_captcha, only: [:create, :update] # Change this to be any actions you want to protect.

  private
  
    def check_captcha
      puts "Verify recaptcha: #{verify_recaptcha}"
      unless verify_recaptcha
        configure_permitted_parameters
        puts "Signup params: #{sign_up_params}"
        self.resource = resource_class.new sign_up_params
        resource.validate # Look for any other validation errors besides Recaptcha
        puts "Validation errors: #{resource.errors.full_messages}"
        respond_with_navigational(resource) { render :new }
      end 
    end
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email])
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/characters/_basicInfo.html.erb
<div class="basicInfo">

  <div class="form-group">
    <div class="control-label col-sm-2">
      <%= f.label :name %>
    </div>
    <div class="col-sm-2">
      <%= f.text_field :name, class: "form-control", placeholder: "Name", autofocus: true %>
    </div>
    <div class="control-label col-sm-2">
      <%= f.label :virtue %>
    </div>
    <div class="col-sm-2">
      <%= f.text_field :virtue, class: "form-control", placeholder: "Virtue", autofocus: true %>
    </div>
    <div class="control-label col-sm-2">
      <%= f.label :chronicle %>
    </div>
    <div class="col-sm-2">
      <%= f.text_field :chronicle, class: "form-control", placeholder: "Chronicle", autofocus: true %>
    </div>
  </div>

  <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :age %>
      </div>
      <div class="col-sm-2">
        <%= f.text_field :age, class: "form-control", placeholder: "Age", autofocus: true %>
      </div>
      <div class="control-label col-sm-2">
        <%= f.label :vice %>
      </div>
      <div class="col-sm-2">
        <%= f.text_field :vice, class: "form-control", placeholder: "Vice", autofocus: true %>
      </div>
      <div class="control-label col-sm-2">
        <%= f.label :faction %>
      </div>
      <div class="col-sm-2">
        <%= f.text_field :faction, class: "form-control", placeholder: "Faction", autofocus: true %>
      </div>
    </div>

    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :player %>
      </div>
      <div class="col-sm-2">
        <%= f.text_field :player, class: "form-control", placeholder: "Player", autofocus: true %>
      </div>
      <div class="control-label col-sm-2">
        <%= f.label :concept %>
      </div>
      <div class="col-sm-2">
        <%= f.text_field :concept, class: "form-control", placeholder: "Concept", autofocus: true %>
      </div>
      <div class="control-label col-sm-2">
        <%= f.label :groupName %>
      </div>
      <div class="col-sm-2">
        <%= f.text_field :groupName, class: "form-control", placeholder: "Group Name", autofocus: true %>
      </div>
    </div>

</div>

app/views/characters/_form.html.erb
<div class='row'>
  <div class = 'col-xs-12'>
    <%= form_for(@character, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    
    <div class="basicInfo">
      <div class="form-group">
        <div class="control-label col-sm-1">
          <%= f.label :name %>
        </div>
        <div class="col-sm-3">
          <%= f.text_field :name, class: "form-control", placeholder: "Name", autofocus: true %>
        </div>
        <div class="control-label col-sm-1">
          <%= f.label :virtue %>
        </div>
        <div class="col-sm-3">
          <%= f.text_field :virtue, class: "form-control", placeholder: "Virtue", autofocus: true %>
        </div>
        <div class="control-label col-sm-1">
          <%= f.label :chronicle %>
        </div>
        <div class="col-sm-3">
          <%= f.text_field :chronicle, class: "form-control", placeholder: "Chronicle", autofocus: true %>
        </div>
      </div>
    
      <div class="form-group">
          <div class="control-label col-sm-1">
            <%= f.label :age %>
          </div>
          <div class="col-sm-3">
            <%= f.text_field :age, class: "form-control", placeholder: "Age", autofocus: true %>
          </div>
          <div class="control-label col-sm-1">
            <%= f.label :vice %>
          </div>
          <div class="col-sm-3">
            <%= f.text_field :vice, class: "form-control", placeholder: "Vice", autofocus: true %>
          </div>
          <div class="control-label col-sm-1">
            <%= f.label :faction %>
          </div>
          <div class="col-sm-3">
            <%= f.text_field :faction, class: "form-control", placeholder: "Faction", autofocus: true %>
          </div>
        </div>
    
        <div class="form-group">
          <div class="control-label col-sm-1">
            <%= f.label :player %>
          </div>
          <div class="col-sm-3">
            <%= f.text_field :player, class: "form-control", placeholder: "Player", autofocus: true %>
          </div>
          <div class="control-label col-sm-1">
            <%= f.label :concept %>
          </div>
          <div class="col-sm-3">
            <%= f.text_field :concept, class: "form-control", placeholder: "Concept", autofocus: true %>
          </div>
          <div class="control-label col-sm-1">
            <%= f.label :groupName %>
          </div>
          <div class="col-sm-3">
            <%= f.text_field :groupName, class: "form-control", placeholder: "Group Name", autofocus: true %>
          </div>
        </div>
    </div>
    
    <br />
    
    <div class="attributes">
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :intelligence %>
        </div>
        <div class="col-sm-2">
          <%= f.number_field :intelligence, class: "form-control", placeholder: "1", autofocus: true %>
        </div>
        <div class="control-label col-sm-2">
          <%= f.label :strength %>
        </div>
        <div class="col-sm-2">
          <%= f.number_field :strength, class: "form-control", placeholder: "1", autofocus: true %>
        </div>
        <div class="control-label col-sm-2">
          <%= f.label :presence %>
        </div>
        <div class="col-sm-2">
          <%= f.number_field :presence, class: "form-control", placeholder: "1", autofocus: true %>
        </div>
      </div>
    
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :wits %>
        </div>
        <div class="col-sm-2">
          <%= f.number_field :wits, class: "form-control", placeholder: "1", autofocus: true %>
        </div>
        <div class="control-label col-sm-2">
          <%= f.label :dexterity %>
        </div>
        <div class="col-sm-2">
          <%= f.number_field :dexterity, class: "form-control", placeholder: "1", autofocus: true %>
        </div>
        <div class="control-label col-sm-2">
          <%= f.label :manipulation %>
        </div>
        <div class="col-sm-2">
          <%= f.number_field :manipulation, class: "form-control", placeholder: "1", autofocus: true %>
        </div>
      </div>
    
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :resolve %>
        </div>
        <div class="col-sm-2">
          <%= f.number_field :resolve, class: "form-control", placeholder: "1", autofocus: true %>
        </div>
        <div class="control-label col-sm-2">
          <%= f.label :stamina %>
        </div>
        <div class="col-sm-2">
          <%= f.number_field :stamina, class: "form-control", placeholder: "1", autofocus: true %>
        </div>
        <div class="control-label col-sm-2">
          <%= f.label :composure %>
        </div>
        <div class="col-sm-2">
          <%= f.number_field :composure, class: "form-control", placeholder: "1", autofocus: true %>
        </div>
      </div>
    </div>
    
    <br />
    
    <div class="skills col-sm-5" style="background-color: gray">
      <% puts "@character.get_skills.count: #{@character.get_skills.count}" %>
      
      <% i = 0 %>
      <% @character.get_skills.each do |s| %>
        <%= form_for(s, :html => {class: "form-horizontal", role: "form"}) do |g| %>
          <div class="form-group">
            <div class="control-label col-sm-4">
              <% puts "s.name: #{s.name}" %>
              <%= g.label :name, s.name %>
            </div>
            <div class="col-sm-5">
              <%= g.text_field :specialty, class: "form-control", placeholder: "specialty", autofocus: true %>
            </div>
            <div class="col-sm-3">
              <%= g.number_field :value, class: "form-control", placeholder: "1", autofocus: true %>
            </div>
          </div>
        <% end %>
      
        <% i += 1 %>
        <% if i % 8 == 0 %>
          <%= puts "break" %>
          <br />
        <% end %>
      
      <% end %>
    </div>
    
    <br />
    
    <div class="otherTraits col-sm-7">
      <div class="leftSide col-sm-6 float-left">
        <% puts "@character.get_skills.count: #{@character.get_skills.count}" %>
      
        <% @character.get_skills.each do |s| %>
          <%= form_for(s, :html => {class: "form-horizontal", role: "form"}) do |g| %>
            <div class="form-group">
              <div class="control-label col-sm-4">
                <% puts "s.name: #{s.name}" %>
                <%= g.label :name, s.name %>
              </div>
              <div class="col-sm-5">
                <%= g.text_field :specialty, class: "form-control", placeholder: "specialty", autofocus: true %>
              </div>
              <div class="col-sm-3">
                <%= g.number_field :value, class: "form-control", placeholder: "1", autofocus: true %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="rightSide col-sm-6 float-right">
        
      </div>
    </div>
       
    
        
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :inventory %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :inventory, rows: 10, class: "form-control", placeholder: "inventory" %>
        </div>
      </div>
        
      <!--<div class="form-group">
        <div class="row">
          <div class="col-sm-offset-2 col-sm-8">
 
          </div>
        </div>
      </div> -->
        
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
    <% end %>

    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to "Cancel request and return to articles listing", characters_path %> ]
    </div>
  </div>
</div>

app/views/characters/new.html.erb
<h1 align="center">
  Create a character
</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "WodRepo" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav navbar-brand">
            <li><%= link_to "WoDRepo", root_path %></li>
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
          <ul class="nav navbar-right col-md-4">
            <% if current_user %>
              <li class="col-md-8 user-name">
                <%= link_to ('<i class="fa fa-user"></i> ' + truncate(current_user.email, length: 25)).html_safe,
                            edit_user_registration_path, title: 'Edit Profile' %>
              </li>
              <li class="col-md-1"> </li>
              <li class="col-md-3 logout"><%= link_to('Logout', destroy_user_session_path,
                                          class: 'btn btn-xs btn-danger', title: 'Logout', :method => :delete) %></li>
            <% else %>
              <li class="col-md-4 pull-right">
                <%= link_to('Sign In', new_user_session_path, class: 'btn btn-primary', title: 'Sign In') %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2018</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<% if current_user %>
  <h3>Welcome: <%= current_user.username %></h3>
<% else %>
  <h2 align="center">Welcome to the World of Darkness Repository!</h2>
  <div class="jumbotron">
  </div>
  
  <p>
    <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary sign-up' %>
  </p>
<% end %>